export const repository = { owner: 'vercel', name: 'next.js', description: 'The React Framework for the Web. Build full-stack web applications with conventions and tooling that help teams ship faster.', stars: 132400, forks: 28400, languages: [{ name: 'TypeScript', value: 58, color: '#3178c6' }, { name: 'JavaScript', value: 28, color: '#f1e05a' }, { name: 'Rust', value: 9, color: '#dea584' }], technologies: ['React', 'TypeScript', 'Turbopack', 'Jest', 'Rust'], structure: ['packages/next/src', 'packages/next-swc', 'test/e2e', 'examples'] }
export const issues = [
  { id: '1842', title: 'Improve Router error handling', labels: ['good first issue', 'router'], difficulty: 'Beginner', match: 92, effort: '2–4 hours', impact: 'Low', skills: ['JavaScript', 'React', 'Testing'], summary: 'Make client-side navigation failures easier to understand and test.' },
  { id: '1834', title: 'Add keyboard navigation to image gallery', labels: ['accessibility', 'help wanted'], difficulty: 'Intermediate', match: 84, effort: '4–8 hours', impact: 'Medium', skills: ['React', 'Accessibility'], summary: 'Support a complete keyboard experience for the gallery component.' },
  { id: '1819', title: 'Document cache invalidation behaviour', labels: ['documentation'], difficulty: 'Beginner', match: 77, effort: '1–2 hours', impact: 'Low', skills: ['MDX', 'Documentation'], summary: 'Clarify cache invalidation examples in the app router documentation.' },
  { id: '1792', title: 'Optimize development compilation cache', labels: ['performance'], difficulty: 'Advanced', match: 61, effort: '1–2 days', impact: 'High', skills: ['Rust', 'Webpack'], summary: 'Investigate cache keys used in incremental compilation.' }
]
export const analysis = { reason: 'The change is scoped to three well-tested files. It uses existing error boundaries and has a clear acceptance criterion.', files: ['Router.js', 'ErrorHandler.js', 'Router.test.js'], modules: ['Client router', 'Error boundary'], dependency: 'No public API changes', ai: 'This issue is a strong first contribution because the fix stays within the client router. Start by tracing how navigation errors reach the error boundary, then add a focused regression test before changing the message.', similarIssues: ['#1751: Preserve navigation errors', '#1664: Router transition warning'], prs: [{ id: '1721', title: 'Handle cancelled transitions consistently', status: 'Merged', author: 'maria-dev' }, { id: '1698', title: 'Add router error regression tests', status: 'Merged', author: 'lee-code' }] }
export const graph = { nodes: [{ id:'issue', position:{x:20,y:160}, data:{label:'Issue #1842'}, type:'issue' }, { id:'router', position:{x:260,y:75}, data:{label:'Router.js'}, type:'file' }, { id:'error', position:{x:260,y:245}, data:{label:'ErrorHandler.js'}, type:'file' }, { id:'react', position:{x:500,y:75}, data:{label:'React Router'}, type:'tech' }, { id:'test', position:{x:510,y:245}, data:{label:'Router.test.js'}, type:'file' }, { id:'pr', position:{x:740,y:160}, data:{label:'PR #1721'}, type:'pr' }], edges: [{id:'e1',source:'issue',target:'router'},{id:'e2',source:'issue',target:'error'},{id:'e3',source:'router',target:'react'},{id:'e4',source:'error',target:'test'},{id:'e5',source:'test',target:'pr'}] }
